### ISSUE TITLE
pulp --help doesn't work on Ubuntu 15.10 with default nodejs package

### ISSUE THREAD

**Issue by leighman** [purescript-contrib/pulp#156]
```
 » node --version
v0.10.25

 » pulp --help
* ERROR: Property 'parse' of object #<Object> is not a function
```

Turns out path module in v0.10.25 has no parse() [https://nodejs.org/dist/v0.10.25/docs/api/path.html].

Is there a version of nodejs the purescript world considers a minimum? Probably needs polyfilling in purescript-node-path if we want to support default Ubuntus.

**Comment by hdgarrood** [comment]
I think most people run their tests on 4.x, so I think that's probably the minimum version. I'm not sure supporting 0.10 is worth the effort, really. I'd rather ask people to update. Compilers are always hopelessly out of date in the default Ubuntu repos anyway, so I don't think that's a good yardstick.

**Comment by ttbodil** [comment]
Agreed. Node 4.x seems like a reasonable minimum to me. People really shouldn't be using nodes older than that for anything serious.

**Comment by hdgarrood** [comment]
Cool. Then I think we can close this. There's already #150 for improving the error when this does happen.
